name: first_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  local_auth: ^2.3.0
  flutter_local_notifications: ^17.2.3
  device_info_plus: ^11.1.0
  flutter_timezone: ^3.0.1
  http: ^1.2.2
  path_provider: ^2.1.4
  image: ^4.3.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
assets:
    - assets/videos/*
    - assets/images/*
flutter:
  uses-material-design: true
  assets:
    - assets/videos/example.mp4
    - assets/videos/example2.mp4
    - assets/videos/example3.mp4
    - assets/videos/example4.mp4
    - assets/images/example.jpeg
    - assets/images/example3x4.jpg
